### ISSUE TITLE
Enable configuration setting via environment variables as well as via properties files

### ISSUE THREAD

**Issue by johnboyes** [ajoecker/gauge-testrail#2]
It is useful to be able to set the configuration properties via environment variables, as well as / instead of via the properties files that the [README documents](https://github.com/ajoecker/gauge-testrail/tree/master/gauge-testrail-sync#use-plugin).

Most operating systems disallow period-separated key names for environment variables, so it would be very useful to also allow the underscore format for environment variables (for example, `TESTRAIL_URL` as well as `testrail.url`).

**Comment by johnboyes** [comment]
@ajoecker I am happy to submit a PR for this.  Am aware that the last commit on this repo was quite some time ago, but hopefully you're still accepting contributions.  I've tried the plugin in the last week and can confirm that it still works :-)

**Comment by ajoecker** [comment]
Hi @johnboyes .

I am happy to :)

feel free

**Comment by johnboyes** [comment]
That's great, thanks @ajoecker, and good timing - I've just submitted #3, grateful if you can have a look and happy to amend if needed.
